### ISSUE TITLE
Некорректная работа поля "Введите имя и фамилию" в регистрации 

### ISSUE THREAD

**Issue by Stuzja** [Ekaterina0801/Pet-Care-App#5]
Необходимо ввести имя и фамилию, однако поле не воспринимает пробел (вылетает ошибка "имя должно быть на русском языке") и разрешает вписать только имя.
![2xA9AbkAiD4](https://user-images.githubusercontent.com/92890104/144760876-9db5ac46-5aa8-4261-a61f-6b215a6283b3.jpg)

**Comment by Ekaterina0801** [comment]
Исправлено
