### ISSUE TITLE
Редактирование дизайна на странице профиля

### ISSUE THREAD

**Issue by Tatayna-san** [Ekaterina0801/Pet-Care-App#8]
1. В иконке добавить кнопку "Добавить")
2. В основной информации убрать породу и перенести ее в паспорт
3. Между краями экрана и иконками основных данных сделать отступы больше
4. Иконки паспорта здоровья сделать блоками с маленьким закруглением краев и тенью

**Comment by Ekaterina0801** [comment]
Исправлено
